### ISSUE TITLE
GlobalData API Error

### ISSUE THREAD

**Issue by Kingsman44** [ChrisMichaelPerezSantiago/covid19#20]
I am trying to use your GlobalData API https://covid19-server.chrismichael.now.sh/api/v1/GlobalDataReports gives Error 502: BAD_GATEWAY

**Comment by ChrisMichaelPerezSantiago** [comment]
_Hi_ @Kingsman44 

_Yes, unfortunately that function **I will eliminate it**, since it is impossible to request the data due to the **large amount** that is in the table._

I understand that yes, you can get the data using the **getGlobalData** function of the API but I still do not recommend it because it takes a while to get the data.

_I'll see what I can do.._

_Sorry for the inconvenience!_

**Comment by ChrisMichaelPerezSantiago** [comment]
_He shows the following error_

```shell
Error 502: BAD_GATEWAY
```
_Since I am using a free version where I have the API hosted and it limits the waiting time to <10s. The premium version yes, extends the waiting time 10+ s_

_Unfortunately I can't buy the premium version since I don't work and I can't pay the monthly fee_
