### ISSUE TITLE
How the global spreadsheet gets updated?

### ISSUE THREAD

**Issue by DonKennethVitug** [ChrisMichaelPerezSantiago/covid19#8]

**Comment by ChrisMichaelPerezSantiago** [comment]
_Hi @DonKennethVitug ,_

_Unfortunately I will be eliminating that function (**PluginManager.getGlobalData()**) in the next API release, since it is impossible to be able to take the data due to the large number of data added to the table._

_In any case, from this [URL](https://docs.google.com/spreadsheets/d/1avGWWl1J19O_Zm0NGTGy2E-fOG05i4ljRfjl87P7FiA/htmlview?ts=5e5e9222#) you can access the table_
