### ISSUE TITLE
Covid19 React Project Implementation.

### ISSUE THREAD

**Issue by kedsnaik** [ChrisMichaelPerezSantiago/covid19#9]
Hello Sir, 

I had a query regarding the package implementation. How do I use it in my react project. Like how do I import the package and use it like any other npm package. I see that there are many functionalities that come with the package but there is no code example of as to how we actually implement it in the code. I tried running the functions from my terminal, but it didn't work. Can you please help me with it so that I can quickly proceed with the development.  I am eagerly waiting your response.

Thank you.

**Comment by ChrisMichaelPerezSantiago** [comment]
_Of course my friend @kedsnaik ,_
_That's what we are for, to help us._

_You must first install the package using the terminal_

```shell
npm i covid19-api
```

_Then in a file with extension `*.js` or `*.ts` you must import the package as follows_

```javascript
const api = require('covid19-api');
```

**index.js file**
_And so on, successively with the other functions._

```javascript
const api = require('covid19-api')

const main = async() =>{
  const capacityInfoUSHealthFacilities = await api.getCapacityInfoUSHealthFacilities();
  console.log(JSON.stringify(capacityInfoUSHealthFacilities , null , 2))
}

main();
```

_Any other questions, questions, you can let me know. In order to help you!!_
